permalink: pretty

exclude:
  - .bowerrc
  - .scss-lint.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - bower.json
  - bin/*

assets:
  dirname: assets
  baseurl: /kickster/assets/

  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

  js_compressor: uglifier
  css_compressor: sass
  gzip: false
  debug: true

baseurl: /kickster/

gems:
  - jekyll-sitemap

ga_analytics: UA-28631876-2
